databaseChangeLog:
  - changeSet:
      id: 1
      author: Ja
      changes:
        - createTable:
            tableName: PATIENTS
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: email
                  type: varchar(255)
                  constraints:
                    unique: true
              - column:
                  name: password
                  type: varchar(255)
              - column:
                  name: id_card_no
                  type: varchar(255)
              - column:
                  name: first_name
                  type: varchar(255)
              - column:
                  name: last_name
                  type: varchar(255)
              - column:
                  name: phone_number
                  type: varchar(255)
              - column:
                  name: birthday
                  type: datetime